language: python
matrix:
  include:
  # - name: linux_py37
  #   python: 3.7
  #   os: linux
  #   before_install:
  #   - wget https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh -O miniconda.sh;
  #   - bash miniconda.sh -b -p $HOME/miniconda
  #   - export PATH=$HOME/miniconda/bin:$PATH
  #   - ls -las /home/travis/miniconda/lib/

  # - name: linux_py38
  #   python: 3.8
  #   os: linux
  #   before_install:
  #   - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  #   - bash miniconda.sh -b -p $HOME/miniconda
  #   - export PATH=$HOME/miniconda/bin:$PATH
  #   - ls -las /home/travis/miniconda/lib/

  - name: linux_py39
    python: 3.9
    os: linux
    before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda install python=3.9 --yes
    - conda install -c conda-forge/label/scikit-learn_rc scikit-learn --yes
    - ls -las /home/travis/miniconda/lib/

  # - name: macosx_py37
  #   os: osx
  #   osx_image: xcode11.3
  #   language: shell
  #   before_install:
  #   - brew install gcc@7
  #   - export CC=gcc-7
  #   - export CXX=g++-7
  #   - wget https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-MacOSX-x86_64.sh -O miniconda.sh;
  #   - bash miniconda.sh -b -p $HOME/miniconda
  #   - export PATH=$HOME/miniconda/bin:$PATH

  # - name: macosx_py38
  #   os: osx
  #   osx_image: xcode11.3
  #   language: shell
  #   before_install:
  #   - brew install gcc@7
  #   - export CC=gcc-7
  #   - export CXX=g++-7
  #   - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
  #   - bash miniconda.sh -b -p $HOME/miniconda
  #   - export PATH=$HOME/miniconda/bin:$PATH

  - name: macosx_py39
    os: osx
    osx_image: xcode11.3
    language: shell
    before_install:
    - brew install gcc@7
    - export CC=gcc-7
    - export CXX=g++-7
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda install python=3.9 --yes
    - conda install -c conda-forge/label/scikit-learn_rc scikit-learn --yes

  # - name: win_py37
  #   os: windows
  #   language: shell
  #   before_install:
  #   - choco install miniconda3 --version=4.7.12.1
  #   - choco install grep
  #   - echo $ChocolateyToolsLocation
  #   - export SYSP=/c/tools/miniconda3
  #   - export PATH=$SYSP:$SYSP/Library/bin:$SYSP/Scripts:$PATH

  # - name: win_py38
  #   os: windows
  #   language: shell
  #   before_install:
  #   - choco install miniconda3
  #   - choco install grep
  #   - echo $ChocolateyToolsLocation
  #   - export SYSP=/c/tools/miniconda3
  #   - export PATH=$SYSP:$SYSP/Library/bin:$SYSP/Scripts:$PATH

  - name: win_py39
    os: windows
    language: shell
    before_install:
    - choco install miniconda3
    - choco install grep
    - echo $ChocolateyToolsLocation
    - export SYSP=/c/tools/miniconda3
    - export PATH=$SYSP:$SYSP/Library/bin:$SYSP/Scripts:$PATH
    - conda install python=3.9 --yes
    - conda install -c conda-forge/label/scikit-learn_rc scikit-learn --yes

install:
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda install pip
- conda install cython
- conda install --file conda_requirements.txt
- pip install -r requirements.txt
- python setup.py build_ext --inplace
- pip freeze
- python setup.py sdist bdist_wheel

script:
- export PYTHONPATH=$TRAVIS_BUILD_DIR
- cd tests
- python test.py

deploy:
  provider: s3
  access_key_id: AKIAIH6I45BAJIHWYAAQ
  secret_access_key: $AWS_SECRET_KEY
  bucket: "traviscibucket"
  upload_dir: $TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER.$TRAVIS_COMMIT/$TRAVIS_JOB_NAME
  local_dir: $TRAVIS_BUILD_DIR/dist
  skip_cleanup: true
  on:
    all_branches: true

#deploy:
#  provider: script
# #script: bash -c "ls -las dist"
#  script: bash -c "echo $NOT_NEEDED"
#  skip_cleanup: true
#  on:
#    branch: dev

notifications:
  email:
    recipients:
    - carlk@msn.com
    on_success: always
    on_failure: always
